version: 2
jobs:
  build:
    working_directory: /go/src/github.com/entrik/kathisto
    environment:
      - DOCKER_TAG: entrik/kathisto
    docker:
      - image: circleci/golang:1.10.2
    steps:
      - checkout
      - run:
          name: Install Glide
          command: go get github.com/Masterminds/glide
      - run:
          name: Download vendored Go dependencies
          command: glide install
      - run:
          name: Download PhantomJS binary
          command: |
            curl -L https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O
            bzip2 -d phantomjs-2.1.1-linux-x86_64.tar.bz2
            tar xopf phantomjs-2.1.1-linux-x86_64.tar
            cp phantomjs-2.1.1-linux-x86_64/bin/phantomjs ./
      - run:
          name: Build Go binary
          command: env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o kathisto
      - setup_remote_docker
      - run:
          name: Build Docker image with binary
          command: docker build --no-cache -t $DOCKER_TAG .
      - run:
          name: Login to DockerHub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Push image to DockerHub
          command: docker push $DOCKER_TAG